### ISSUE TITLE
Can't create branch ?

### ISSUE THREAD

**Issue by deionalims** [lgmorand/MMM-Transilien#4]
Bonjour,

Je me suis amusé a ajouter une configuration pour afficher le temps restant avant l'arrivée des prochains trains.
Je voulais pousser la branche et proposer une PR mais apparemment je ne peux pas ?

Si vous êtes intéressé je serai ravi de partager mon code.

FX

**Comment by lgmorand** [comment]
Salut FX

Avec plaisir mais le plus simple c'est que tu fork, fasse tes modifs et après fasse une pull request
petite explication ici :)
https://www.youtube.com/watch?v=yr6IzOGoMsQ

**Comment by deionalims** [comment]
C'est fait :)
