### ISSUE TITLE
Deux trajets différents

### ISSUE THREAD

**Issue by Carote** [lgmorand/MMM-Transilien#9]
Bonjour,

J'utilisais ce module Transilien jusque-là sans problème particulier pour avoir les horaires de Courbevoie à Saint Lazare (oui, comme l'exemple !) et j'aimerais pouvoir afficher les horaires des prochains passages pour 2 trajets différents. Par exemple, les prochains trains de Courbevoie à Saint Lazare et ceux de La Garenne Colombes vers Pont Cardinet
En dédoublant le module, cela ne semble pas fonctionner : j'obtiens les mêmes horaires (et noms des trains) du 2ème dans le 1er... 
Je pensais qu'un souci de synchronisation des requêtes empêchait d'avoir le bons résultats, alors j'ai ajouté une durée via initialLoadDelay de 1000 à 30 000ms, mais pas d'amélioration.
J'ai essayé de créer deux lignes différentes dans le même module via lines [ ] comme cela est fait dans le module MMM-Paris-RATP-PG, mais là je n'obtiens plus de résultats...
Quelqu'un a-t-il déjà utilisé ce module MMM-Transilien pour 2 trajets différents ?
Merci d'avance pour votre aide
(Très bon module par ailleurs, hormis l'obtention de l'API, mais il faut être patient !)

**Comment by lgmorand** [comment]
Hello

De memoire, tu peux pas doublonner (ca existait pas a l'epoque). La solution installer deux fois le plugin et editer le code de l'un pr lui donner un nom unique. Regarde s'il n'a pas une propriété pluginanme ou un truc du genre


Je dis bien de memoire. Quatre ans plus tard j'en sais plus grand chose 😁

**Comment by Carote** [comment]
Re,

Merci pour la réponse rapide !
Je ne voulais pas trop me lancer et changer le code... mais du coup j'ai testé : j'ai copié/collé le dossier d'origine et renommé en MMM-Transilien2, j'ai renommé (dans ce nouveau dossier) le fichier MMM-Transilien.js en MMM-Transilien2.js, puis j'ai ouvert ce fichier pour remplacer MMM-Transilien par MMM-Transilien2 au début du fichier (ligne 9) et enfin, j'ai modifié le nom du module appelé dans le fichier config.js en MMM-Transilien2 et... ça fonctionne très bien !
A voir si toute ces modifications sont nécessaires, mais avec tout ça, ça fonctionne
Si ça peut servir à quelqu'un d'autre ;-)
Merci encore LG !
